# Generated by Django 5.2.4 on 2025-11-21 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariopersonalizado',
            options={'verbose_name': 'Usuario Personalizado', 'verbose_name_plural': 'Usuarios Personalizados'},
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Se establece automáticamente cuando se crea el usuario', verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, help_text='Se establece cuando el usuario es eliminado (soft-delete)', null=True, verbose_name='Fecha de Eliminación'),
        ),
    ]
