# Generated by Django 5.2.4 on 2025-12-08 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0002_alter_usuariopersonalizado_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('view_dashboard', 'Ver Dashboard'), ('Ver Anomalias', 'view_anomalies'), ('view_events', 'Ver Eventos'), ('create_ticket', 'Crear Tickets en GLPI'), ('Editar Anomalia', 'edit_anomaly'), ('Descargar Reportes', 'download_report'), ('manage_users', 'Gestionar Usuarios'), ('Gestionar Roles', 'manage_roles'), ('Configurar Alertas', 'configure_alerts'), ('admin_access', 'Acceso Administrador')], help_text='Identificador unico del permiso', max_length=50, unique=True, verbose_name='Nombre del Permiso')),
                ('descripcion', models.TextField(help_text='Descripcion clara de que permite este permiso', verbose_name='Descripcion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
            ],
            options={
                'verbose_name': ('Permiso',),
                'verbose_name_plural': ('Permisos',),
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='usuariopersonalizado',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Usuario Personalizado', 'verbose_name_plural': 'Usuarios Personalizados'},
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='debe_cambiar_contrasena',
            field=models.BooleanField(default=False, help_text='¿Fuerza al usuario a cambiar su contraseña en el próximo inicio de sesión?', verbose_name='Debe Cambiar Contraseña'),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='es_activo',
            field=models.BooleanField(default=True, help_text='¿Puede el usuario acceder al sistema?', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='intentos_login',
            field=models.IntegerField(default=0, help_text='Contador de intentos fallidos (se resetea con login exitoso)', verbose_name='Intentos de Login Fallidos'),
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='ultimo_acceso',
            field=models.DateTimeField(blank=True, help_text='Marca de tiempo del último acceso al sistema', null=True, verbose_name='Último Acceso'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('admin', 'Administrador'), ('auditor', 'Auditor'), ('viewer', 'Visualizador')], max_length=50, unique=True, verbose_name='Nombre del Rol')),
                ('descripcion', models.TextField(help_text='Descripcion clara del rol y sus responsabilidades', verbose_name='Descripcion')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('archivo', models.BooleanField(default=True, help_text='Si el rol esta activo para nuevas asignaciones', verbose_name='Activo')),
                ('permisos', models.ManyToManyField(help_text='Permisos asignados a este rol', related_name='roles', to='usuarios.permission', verbose_name='Permisos')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='rol',
            field=models.ForeignKey(blank=True, help_text='Rol asignado al usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.role', verbose_name='Rol'),
        ),
        migrations.AddIndex(
            model_name='usuariopersonalizado',
            index=models.Index(fields=['username'], name='usuarios_us_usernam_fc6d56_idx'),
        ),
        migrations.AddIndex(
            model_name='usuariopersonalizado',
            index=models.Index(fields=['email'], name='usuarios_us_email_4302c7_idx'),
        ),
        migrations.AddIndex(
            model_name='usuariopersonalizado',
            index=models.Index(fields=['rol'], name='usuarios_us_rol_id_947a66_idx'),
        ),
        migrations.AddIndex(
            model_name='usuariopersonalizado',
            index=models.Index(fields=['es_activo'], name='usuarios_us_es_acti_c88afe_idx'),
        ),
    ]
