# Generated by Django 5.2.4 on 2025-12-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_permission_alter_usuariopersonalizado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='nombre',
            field=models.CharField(choices=[('view_dashboard', 'Ver Dashboard'), ('view_anomalies', 'Ver Anomalias'), ('view_events', 'Ver Eventos'), ('create_ticket', 'Crear Tickets en GLPI'), ('Editar Anomalia', 'edit_anomaly'), ('Descargar Reportes', 'download_report'), ('Gestionar Usuarios', 'manage_users'), ('Gestionar Roles', 'manage_roles'), ('configure_alerts', 'Configurar Alertas'), ('admin_access', 'Acceso Administrador')], help_text='Identificador unico del permiso', max_length=50, unique=True, verbose_name='Nombre del Permiso'),
        ),
    ]
