# Generated by Django 5.2.4 on 2025-12-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_permission_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='nombre',
            field=models.CharField(choices=[('view_dashboard', 'Ver Dashboard'), ('view_anomalies', 'Ver Anomalias'), ('Ver Eventos', 'view_events'), ('create_ticket', 'Crear Tickets en GLPI'), ('edit_anomaly', 'Editar Anomalia'), ('Descargar Reportes', 'download_report'), ('Gestionar Usuarios', 'manage_users'), ('manage_roles', 'Gestionar Roles'), ('Configurar Alertas', 'configure_alerts'), ('admin_access', 'Acceso Administrador')], help_text='Identificador unico del permiso', max_length=50, unique=True, verbose_name='Nombre del Permiso'),
        ),
        migrations.AlterField(
            model_name='role',
            name='nombre',
            field=models.CharField(choices=[('Administrador', 'admin'), ('auditor', 'Auditor'), ('Visualizador', 'viewer')], max_length=50, unique=True, verbose_name='Nombre del Rol'),
        ),
    ]
