# Generated by Django 5.2.4 on 2025-12-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_permission_nombre_alter_role_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='archivo',
            new_name='activo',
        ),
        migrations.AlterField(
            model_name='permission',
            name='nombre',
            field=models.CharField(choices=[('view_dashboard', 'Ver Dashboard'), ('view_anomalies', 'Ver Anomalias'), ('view_events', 'Ver Eventos'), ('create_ticket', 'Crear Tickets en GLPI'), ('edit_anomaly', 'Editar Anomalia'), ('download_report', 'Descargar Reportes'), ('manage_users', 'Gestionar Usuarios'), ('manage_roles', 'Gestionar Roles'), ('configure_alerts', 'Configurar Alertas'), ('admin_access', 'Acceso Administrador')], help_text='Identificador unico del permiso', max_length=50, unique=True, verbose_name='Nombre del Permiso'),
        ),
        migrations.AlterField(
            model_name='role',
            name='nombre',
            field=models.CharField(choices=[('admin', 'Administrador'), ('auditor', 'Auditor'), ('viewer', 'Visualizador')], max_length=50, unique=True, verbose_name='Nombre del Rol'),
        ),
    ]
