# Generated by Django 5.2.4 on 2025-12-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_rename_archivo_to_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['nombre'], 'verbose_name': 'Permiso', 'verbose_name_plural': 'Permisos'},
        ),
        migrations.AlterField(
            model_name='permission',
            name='nombre',
            field=models.CharField(help_text='Identificador único del permiso (ej: view_dashboard)', max_length=50, unique=True, verbose_name='Nombre del Permiso'),
        ),
        migrations.AlterField(
            model_name='role',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='role',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
    ]
