# Generated by Django 5.2.4 on 2025-09-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoDeAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_usuario', models.EmailField(help_text='Email del usuario que realizo la accion', max_length=254)),
                ('direccion_ip', models.GenericIPAddressField(help_text='Direccion IP desde dinde se realizo la acciob')),
                ('timestamp', models.DateTimeField()),
                ('archivo_id', models.CharField(max_length=255)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo_evento', models.CharField(help_text="Ej: 'view', 'download', 'edit'", max_length=50)),
                ('es_anomalia', models.BooleanField(default=False, help_text='Marcado por el modelo de IA como una anomalía.')),
                ('detalles', models.JSONField(blank=True, help_text='Datos originales en crudo de la API.', null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
