# Generated by Django 5.2.4 on 2025-11-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoDeAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_usuario', models.EmailField(help_text='Email del usuario que realizo la accion', max_length=254)),
                ('direccion_ip', models.GenericIPAddressField(help_text='Direccion IP desde dinde se realizo la accion')),
                ('timestamp', models.DateTimeField()),
                ('archivo_id', models.CharField(max_length=255, unique=True)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo_evento', models.CharField(help_text="Ej: 'view', 'download', 'edit'", max_length=50)),
                ('es_anomalia', models.BooleanField(default=False, help_text='Marcado por el modelo de IA como una anomalía.')),
                ('detalles', models.JSONField(blank=True, help_text='Datos originales en crudo de la API.', null=True)),
            ],
            options={
                'verbose_name': 'Evento de Acceso',
                'verbose_name_plural': 'Eventos de Acceso',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['email_usuario', '-timestamp'], name='idx_email_timestamp'), models.Index(fields=['es_anomalia', '-timestamp'], name='idx_anomalia_timestamp'), models.Index(fields=['tipo_evento', '-timestamp'], name='idx_tipo_timestamp'), models.Index(fields=['archivo_id'], name='idx_archivo_id'), models.Index(fields=['timestamp'], name='idx_timestamp')],
            },
        ),
    ]
