# Generated by Django 5.2.4 on 2025-12-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0002_add_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventodeacceso',
            name='anomaly_score',
            field=models.FloatField(blank=True, help_text='Score de Anomalia: 0.0 (Normal) a 1.0 (Anomalo)', null=True),
        ),
        migrations.AddField(
            model_name='eventodeacceso',
            name='fecha_alerta',
            field=models.DateTimeField(blank=True, help_text='Cuando se envio la alerta', null=True),
        ),
        migrations.AddField(
            model_name='eventodeacceso',
            name='severidad',
            field=models.CharField(blank=True, choices=[('BAJA', 'Baja - Monitoreo'), ('MEDIA', 'Media - Revisar Pronto'), ('ALTA', 'Alta - Revisar Hoy'), ('CRITICA', 'Critica - Accion Inmediata')], default=None, help_text='Nivel de criticidad de la anomalia', max_length=20, null=True),
        ),
    ]
