# Generated by Django 5.2.4 on 2025-12-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0003_eventodeacceso_anomaly_score_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='eventodeacceso',
            name='idx_tipo_timestamp',
        ),
        migrations.RemoveIndex(
            model_name='eventodeacceso',
            name='idx_archivo_id',
        ),
        migrations.AddField(
            model_name='eventodeacceso',
            name='id_evento_google',
            field=models.CharField(help_text='ID unico del evento en Google Drive Activity API', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='eventodeacceso',
            name='archivo_id',
            field=models.CharField(help_text='ID del archivo en Google Drive', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventodeacceso',
            name='direccion_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Direccion IP desde dinde se realizo la accion', null=True),
        ),
        migrations.AlterField(
            model_name='eventodeacceso',
            name='nombre_archivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventodeacceso',
            name='timestamp',
            field=models.DateTimeField(help_text='Fecha y hora exacta del evento (UTC)'),
        ),
        migrations.AlterField(
            model_name='eventodeacceso',
            name='tipo_evento',
            field=models.CharField(help_text="Ej: 'view', 'download', 'edit', move", max_length=50),
        ),
        migrations.AddIndex(
            model_name='eventodeacceso',
            index=models.Index(fields=['tipo_evento'], name='idx_tipo_evento'),
        ),
        migrations.AddIndex(
            model_name='eventodeacceso',
            index=models.Index(fields=['id_evento_google'], name='idx_id_google'),
        ),
    ]
