# Generated by Django 5.2.4 on 2025-12-17 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0004_remove_eventodeacceso_idx_tipo_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GLPITicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField(help_text='ID del ticket en el sistema GLPI externo', unique=True)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('en_curso', 'En Curso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='nuevo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('enlace_glpi', models.URLField(blank=True, help_text='Link directo al ticket en GLPI', null=True)),
            ],
            options={
                'verbose_name': 'Ticket GLPI',
                'verbose_name_plural': 'Tickets GLPI',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.RemoveIndex(
            model_name='eventodeacceso',
            name='idx_email_timestamp',
        ),
        migrations.RemoveIndex(
            model_name='eventodeacceso',
            name='idx_anomalia_timestamp',
        ),
        migrations.RemoveIndex(
            model_name='eventodeacceso',
            name='idx_timestamp',
        ),
        migrations.RemoveIndex(
            model_name='eventodeacceso',
            name='idx_tipo_evento',
        ),
        migrations.RemoveIndex(
            model_name='eventodeacceso',
            name='idx_id_google',
        ),
        migrations.RemoveField(
            model_name='eventodeacceso',
            name='fecha_alerta',
        ),
        migrations.AlterField(
            model_name='eventodeacceso',
            name='anomaly_score',
            field=models.FloatField(default=0.0, help_text='Score de Anomalia: 0.0 (Normal) a 1.0 (Anomalo)'),
        ),
        migrations.AlterField(
            model_name='eventodeacceso',
            name='archivo_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID del archivo en Google Drive', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventodeacceso',
            name='email_usuario',
            field=models.EmailField(db_index=True, help_text='Email del usuario que realizo la accion', max_length=254, verbose_name='Usuario Actor'),
        ),
        migrations.AlterField(
            model_name='eventodeacceso',
            name='es_anomalia',
            field=models.BooleanField(db_index=True, default=False, help_text='Marcado por el modelo de IA como una anomalía.'),
        ),
        migrations.AlterField(
            model_name='eventodeacceso',
            name='id_evento_google',
            field=models.CharField(default='temp_default_value', help_text='ID unico del evento en Google Drive Activity API', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventodeacceso',
            name='severidad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], db_index=True, default='BAJA', help_text='Nivel de criticidad de la anomalia', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventodeacceso',
            name='timestamp',
            field=models.DateTimeField(db_index=True, help_text='Fecha y hora exacta del evento (UTC)', verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='eventodeacceso',
            name='tipo_evento',
            field=models.CharField(db_index=True, help_text="Ej: 'view', 'download', 'edit', move", max_length=50),
        ),
        migrations.AddIndex(
            model_name='eventodeacceso',
            index=models.Index(fields=['email_usuario', 'timestamp'], name='idx_user_time'),
        ),
        migrations.AddIndex(
            model_name='eventodeacceso',
            index=models.Index(fields=['es_anomalia', 'severidad'], name='idx_anomaly_sev'),
        ),
        migrations.AddField(
            model_name='glpiticket',
            name='evento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_glpi', to='monitoreo.eventodeacceso', verbose_name='Evento Anómalo'),
        ),
    ]
