# Generated by Django 5.2.4 on 2025-12-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0005_glpiticket_remove_eventodeacceso_idx_email_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventodeacceso',
            name='motivo_anomalia',
            field=models.CharField(blank=True, help_text='Explicación heurística de por qué se detectó como anomalía', max_length=255, null=True),
        ),
    ]
